on:
  push:
    tags:
      - 'v*'

name: Release WASM files

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: '0.27.0'
      - name: build
        run: |
          make build
      - name: Compress directory
        run: zip -j release.zip build/*.wasm

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: release_artifact
          path: release.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip