on: pull_request
name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: '0.27.0'
      - name: build
        run: |
          make build